apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orders-web-hpa
  namespace: ecommerce-dev
  labels:
    env: dev
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    kind: Deployment
    name: orders-web
    apiVersion: apps/v1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 60
          type: Percent
          value: 100