apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: reports-ns
spec:
  podSelector:
    matchLabels:
      app: reports-api
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8080
      from:
        - podSelector:
            matchLabels:
              app: reports-web