apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      volumeMounts:
        - mountPath: /etc/secrets
          name: db-url
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: app-secret
  volumes:
    - name: db-url
      secret:
        secretName: app-secret
        items:
          - key: db-url
            path: db-url
