apiVersion: v1
kind: Service
metadata:
  name: order-redis
  namespace: ecommerce-dev
  labels:
    env: dev
spec:
  type: ClusterIP
  selector:
    app: orders-redis
    tier: cache
    env: dev
  ports:
    - port: 6379
      targetPort: 6379