apiVersion: v1
kind: Pod
metadata:
  name: gpu-app
spec:
  containers:
    - name: gpu-app
      image: cuda:11.0
  tolerations:
    - key: hardware
      operator: Equal
      value: gpu
      effect: NoSchedule
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: gpu
                operator: In
                values:
                  - true
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disk
                operator: NotIn
                values:
                  - hdd