apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: dev
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: guestbook
          image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
          ports:
            - containerPort: 80
          env:
            - name: GET_HOSTS_FROM
              valueFrom:
                configMapKeyRef:
                  key: GET_HOSTS_FROM
                  name: frontend-config
          resources:
            requests:
              cpu: 100m
              memory: 100Mi


