apiVersion: batch/v1
kind: Job
metadata:
  name: db-backup
spec:
  template:
    metadata:
      name: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:15
          command:
            - pg_dump mydb > /backup/mydb.sql
          restartPolicy: Never
  completions: 3
  parallelism: 2
  backoffLimit: 4