apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: staging-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: staging-role
subjects:
  - kind: ServiceAccount
    name: cicd-sa
    namespace: staging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: staging-c-rb
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: staging-prod-role
subjects:
  - kind: ServiceAccount
    name: cicd-sa
    namespace: staging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prod-c-rb
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: staging-prod-role
subjects:
  - kind: ServiceAccount
    name: cicd-sa
    namespace: staging