apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: ecommerce-dev
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: database
      env: dev
  template:
    metadata:
      labels:
        app: postgres
        tier: database
        env: dev
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            tcpSocket:
              port: 5432
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            tcpSocket:
              port: 5432
  volumeClaimTemplates:
    - metadata:
        labels:
          env: dev
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
         requests:
           storage: 10Gi
